@startuml
hide circle
hide empty methods
hide empty attributes

class Stage{
    lieu
    dateDebut
    dateFin
    nomTuteurEntreprise
    theme
    noteStage
}

class Entreprise{
    nom
    adresse
    siegeSocial
}

class Promotion{
 
}

class Etudiant{
    numINE
    nom
    prenom
    moyenneGenerale
}

class GroupeTP{
    nom
}

class GroupeTD{
    nom
}

class Enseignant {
    nom
    prenom
    specialite
}

Stage "*" -- "1" Entreprise
Stage -"1" Promotion
Stage --"0..1" Tuteur

Etudiant -"1" GroupeTP
GroupeTP -"1" GroupeTD
GroupeTD --"1" Promotion
Tuteur -|> Enseignant

@enduml
